name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1.12.0
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
    
    - name: Get latest Domoticz build
      id: versions
      run: |
        curl -ksL https://releases.domoticz.com/releases/beta/version_linux_x86_64.h --output version.h
        if [ $? -ne 0 ]
        then
          echo "Error downloading version file!";
        exit 1
        fi

        declare $(cat version.h | awk '{print $2"="$3}')
        RELEASE_DATE="$(date -d @$APPDATE -u +"%Y-%m-%dT%H:%M:%SZ")"
        BETA_VERSION=2023
        echo "Building release $BETA_VERSION.$APPVERSION from commit $APPHASH ($RELEASE_DATE)";

        # Remove double quotes in APPHASH
        APPHASH="${APPHASH%\"}"
        APPHASH="${APPHASH#\"}"
        echo "::set-output name=APPHASH::$APPHASH"
        echo "::set-output name=RELEASE_DATE::$RELEASE_DATE"
        echo "::set-output name=APPVERSION::$APPVERSION"
        echo "::set-output name=BETA_VERSION::$BETA_VERSION"
        
    - name: Build docker images
      run: |
        docker buildx build --push \
        --no-cache \
        --platform linux/arm/v7,linux/arm64,linux/amd64,linux/386 \
        --build-arg APP_VERSION=${{ steps.versions.outputs.APPVERSION }} \
        --build-arg APP_HASH=${{ steps.versions.outputs.APPHASH  }} \
        --build-arg BUILD_DATE=${{ steps.versions.outputs.RELEASE_DATE }} \
        --tag interxis/domoticz:latest \
        --tag interxis/domoticz:beta \
        --tag interxis/domoticz:${{ steps.versions.outputs.BETA_VERSION }}-beta.${{ steps.versions.outputs.APPVERSION }} \
        .
    
